version: "3"

tasks:
  setup:
    cmds:
      - npm install --save-dev --save-exact prettier release-please
  fmt:
    cmds:
      - npx prettier --write .
      - go fmt ./...
  mod:
    cmds:
      - go mod tidy
      - go mod vendor
  test:
    cmds:
      - go clean -testcache
      - go test -p=1 ./...
